import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/home.module.css'
import Navbar from '../componentes/Navbar'

export default function Home() {
  return (
    <div className={styles.container}>
     
      <Head>
        <title>toxico</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     


      <main className={styles.main}>
      <video  autoPlay muted loop className={styles.videofundo} > 
                 
                 <source src={"/mundo.mp4" }type="video/mp4"/>       
             </video>
      
        <h1 className={styles.title}>
          Mente Aberta! <a href="/destaque">DESTAQUEnews</a>
        </h1>
        <p className={styles.description}>
          {' '}
          
        </p>
        <Image src={'/radioativo.jpg'}width={600}height={300}></Image>
        

       

        <div className={styles.grid}>
          <a href="/filme" className={styles.card}>
            <h2>FILMES &rarr;</h2>
            <p>Melhores filmes e lancamentos 2022</p>
          </a>

          <a href="/serie" className={styles.card}>
            <h2>Series &rarr;</h2>
            <p>as series que voce mais gosta de assistir</p>
          </a>

          <a
            href="/desenho"
            className={styles.card}
          >
            <h2>desenhos animados &rarr;</h2>
            <p>pra criançada curtir o dia todo!</p>
          </a>

          <a
            href="/jogos"
            className={styles.card}
          >
            <h2>jogos&rarr;</h2>
            <p>
              tudo sobre os melhores jogos da atualidade
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href=""
          target="_blank"
          rel="noopener noreferrer"
        >
          criacao:{' '}
          <span className={styles.logo}>
            <Image src="/radioativo.jpg" alt="Logo" width={72} height={56} />
          </span>
        </a>
      </footer>
    </div>
  )
}
